# Generated by Django 3.0.2 on 2020-04-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=40)),
                ('contact_no', models.TextField(max_length=10)),
                ('email', models.TextField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('proof_id_no', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
    ]
